synonyms = [
    {'text1': 'ps4', 'text2': 'playstation 4', 'synonym_type': 'T'},
    {'text1': 'philips', 'text2': 'phillips', 'synonym_type': 'T'},
    {'text1': 'animal', 'text2': 'pet', 'synonym_type': 'T'},
    {'text1': 'animal', 'text2': 'lion', 'synonym_type': 'O'},
    {'text1': 'pet', 'text2': 'cat', 'synonym_type': 'O'},
    {'text1': 'pet', 'text2': 'dog', 'synonym_type': 'O'},
    {'text1': 'wow', 'text2': 'world of warcraft', 'synonym_type': 'T'},
    {'text1': 'cat', 'text2': 'garfield', 'synonym_type': 'O'},
    {'text1': 'playstation 3', 'ps3': '', 'synonym_type': 'T'},
    {'text1': 'gta v', 'text2': 'gta 5', 'synonym_type': 'T'},
    {'text1': 'new york', 'text2': 'new york city', 'synonym_type': 'T'},
    {'text1': 'new york city', 'text2': 'nyc', 'synonym_type': 'T'},
    {'text1': 'nyc', 'text2': 'new york', 'synonym_type': 'T'},
]
